export const CDN_URL ="https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";
export const restaurantsData = [
    {
        id: "65797",
        name:"Leon's - Burgers & Wings (Leon Grill)",
        image_id: "b2edbc28b7b8219d6e0a9c049ce06658",
        locality: "Koramangala",
        area_name: "Koramangala",
        cost_for_two: "₹300 for two",
        cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
        avg_rating: 4.4,
        total_ratings: "10K+",
        sla_delivery_time: 29,
        sla_last_mile_travel: 6.1,
        availability_next_close_time: "2024-02-07 04:00:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/leons-burgers-and-wings-leon-grill-koramangala-bangalore-65797"
    },
    {
        id: "77949",
        name:"Burger King",
        image_id: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
        locality: "Gandhi Bazar",
        area_name: "Basavanagudi",
        cost_for_two: "₹350 for two",
        cuisines: ["Burgers", "American"],
        avg_rating: 4.2,
        total_ratings: "10K+",
        sla_delivery_time: 25,
        sla_last_mile_travel: 3,
        availability_next_close_time: "2024-02-07 05:00:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/burger-king-gandhi-bazar-basavanagudi-bangalore-77949"
    },
    {
        id: "272031",
        name: "Baskin Robbins",
        image_id: "85ccae4e3576f9330af102c46ca85395",
        locality: "5th Block",
        area_name: "Koramangala",
        cost_for_two: "₹150 for two",
        cuisines: ["Desserts"],
        avg_rating: 4.4,
        veg: true,
        total_ratings: "100+",
        sla_delivery_time: 26,
        sla_last_mile_travel: 5.7,
        availability_next_close_time: "2024-02-13 00:00:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/baskin-robbins-5th-block-koramangala-bangalore-272031"
    },
    {
        id: "341895",
        name: "Burger Seigneur",
        image_id: "k4z46joj5ozirqpyww1z",
        locality: "Indiranagar",
        area_name: "Indiranagar",
        cost_for_two: "₹1300 for two",
        cuisines: ["American", "Continental", "Burgers", "Beverages"],
        avg_rating: 4.4,
        total_ratings: "1K+",
        sla_delivery_time: 36,
        sla_last_mile_travel: 8.2,
        availability_next_close_time: "2024-02-07 02:59:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/burger-seigneur-indiranagar-bangalore-341895"
    },
    {
        id: "506324",
        name: "Louis Burger",
        image_id: "19d3d352cc815b9d88b22617b41fa97b",
        locality: "6Th Block, Koramangala",
        area_name: "Koramangala",
        cost_for_two: "₹600 for two",
        cuisines: ["Burgers", "American", "Fast Food"],
        avg_rating: 4.4,
        total_ratings: "1K+",
        sla_delivery_time: 34,
        sla_last_mile_travel: 5.6,
        availability_next_close_time: "2024-02-07 04:00:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/louis-burger-6th-block-koramangala-bangalore-506324"
    },
    {
        id: "23700",
        name: "McDonald's",
        image_id: "03501c33ecb3a3105124441e541e6fe4",
        locality: "2nd Stage",
        area_name: "Banashankari",
        cost_for_two: "₹400 for two",
        cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
        avg_rating: 4.3,
        total_ratings: "10K+",
        sla_delivery_time: 28,
        sla_last_mile_travel: 5.9,
        availability_next_close_time: "2024-02-07 02:45:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/mcdonalds-2nd-stage-banashankari-bangalore-23700"
    },
    {
        id: "17301",
        name: "KFC",
        image_id: "f01666ac73626461d7455d9c24005cd4",
        locality: "Vani Vilas Road",
        area_name: "Basavanagudi",
        cost_for_two: "₹400 for two",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        avg_rating: 4.2,
        total_ratings: "10K+",
        sla_delivery_time: 28,
        sla_last_mile_travel: 3,
        availability_next_close_time: "2024-02-07 02:00:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/kfc-vani-vilas-road-basavanagudi-bangalore-17301"
    },
    {
        id: "45871",
        name: "Subway",
        image_id: "63178e3e64d503a479f2a2048a474552",
        locality: "Brigade Road",
        area_name: "Central Bangalore",
        cost_for_two: "₹350 for two",
        cuisines: ["Fast Food", "Salads", "Snacks", "Desserts", "Beverages"],
        avg_rating: 4.2,
        total_ratings: "10K+",
        sla_delivery_time: 28,
        sla_last_mile_travel: 3.6,
        availability_next_close_time: "2024-02-07 02:00:00",
        is_open: true,
        link: "https://www.swiggy.com/restaurants/subway-brigade-road-central-bangalore-bangalore-45871"
    },
    // Add more restaurant objects here
  ];